#+TITLE: My ratpoison configuration

** Disable "Welcome" message.

I disabled the default welcome message on start up RP.

#+begin_src sh :tangle ~/.ratpoisonrc
startup_message off
#+end_src

** Unmanaged window list.

Add name to the list of unmanaged windows. Thus, windows of this name will not be managed but allowed to
choose their position themselves.

#+begin_src sh :tangle ~/.ratpoisonrc
unmanage xmessage
unmanage MPlayer
#+end_src

** RP "The best wm for smaller screens!"

I use Ratpoison on tiny 10 inch screen. So I disabled borders/panels etc..

#+begin_src sh :tangle ~/.ratpoisonrc
set padding 0 0 0 0
set barborder 0
set border 0
#+end_src

** Default font.

I prefer XFT fonts for information stuff.

#+begin_src sh :tangle ~/.ratpoisonrc
set font "DejaVu Sans Mono-10"
#+end_src

** Appearance.

#+begin_src sh :tangle ~/.ratpoisonrc
set winfmt [%n] %s %t
set winname class
set winliststyle column
set wingravity c
set bargravity ne
set maxsizegravity c
#+end_src

** Bar's timeout in seconds.

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
msgwait 5
#+end_src

** Don't change the cursor into a square when waiting for a key.

#+begin_src sh :tangle ~/.ratpoisonrc
set waitcursor 0
#+end_src

** Rudeness.

#+begin_src sh :tangle ~/.ratpoisonrc
# Rudeness is a bitwise or of the following values:
# 1 Transient windows may raise.
# 2 Normal windows may raise.
# 4 New transient windows end up in the foreground.
# 8 New normal windows end up in the foreground.
rudeness 12
#+end_src

** When the hook is run, command will be executed.

1. =C-t b= when you switch to a different window in the current frame.
2. Display information about the current window when you switch to a different window.
3. Display information about the current window when you switch to a different frame.

#+begin_src sh :tangle ~/.ratpoisonrc
addhook switchwin banish
addhook switchwin info [%n] %t
addhook switchframe info [%n] %t
#+end_src

** Key bindings.

*** Windows/Frames

#+begin_src sh :tangle ~/.ratpoisonrc
bind z windows
bind o only
bind u undo
bind d dedicate
bind g groups
#+end_src

*** Run-or-raise

Get the runorraise script form [[https://raw2.github.com/ivoarch/bin/master/ratpoison/runorraise.pl][here]].

#+begin_src sh :tangle ~/.ratpoisonrc
bind a exec ~/bin/ratpoison/rat_info.sh
bind c exec ~/bin/ratpoison/runorraise.pl URxvt 'urxvt'
alias emacs exec ~/bin/ratpoison/runorraise.pl Emacs 'emacsclient -ca emacs'
bind e emacs
alias conkeror exec ~/bin/ratpoison/runorraise.pl Conkeror 'conkeror'
bind w conkeror
#+end_src

*** Function

Open *man* pages from RP.

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
bind m exec ratpoison -c "exec urxvt -e man $(ratpoison -c "prompt Manpage:")"
#+end_src

Show Dropbox status.

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
bind D exec ratpoison -c "echo `dropbox status`"
#+end_src

Show info script.

Get the ratpoison-info script from [[https://raw2.github.com/ivoarch/bin/master/ratpoison/rat_info.sh][here]].

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
bind a exec ~/bin/ratpoison/rat_info.sh
#+end_src

Show *root* window.

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
alias showroot exec ratpoison -c fdump > FOO; ratpoison -c 'select -' -c only
alias unshowroot exec ratpoison -c "frestore `cat FOO`"
bind B showroot
bind M-B unshowroot
#+end_src

Toggle =on|off= energy saving.

Get the script from [[https://raw2.github.com/ivoarch/bin/master/system/dpms-toggle.sh][here]].

#+begin_src sh :tangle ~/.ratpoisonrc
alias screensaver exec ~/bin/system/dpms-toggle.sh
bind Pause screensaver
#+end_src

Toggle =on|off= touchpad.

Get the script from [[https://raw2.github.com/ivoarch/bin/master/system/touchpad_toggle][here]].

#+BEGIN_SRC sh :tangle ~/.ratpoisonrc
alias toggletouchpad exec ~/bin/system/touchpad_toggle
bind BackSpace toggletouchpad
#+END_SRC

Take a screenshot.

#+begin_src sh :tangle ~/.ratpoisonrc
alias ratshot exec import -window root png:$HOME/Pictures/Screenshots/ratpoison-$(date +%s)$$.png && ratpoison -c "echo Ratshot saved!"
definekey top Print ratshot
#+end_src

*** Other.

Abort keystrokes.

#+begin_src sh :tangle ~/.ratpoisonrc
definekey root Escape abort
#+end_src


*** Multimedia keys.

Audio/Volume keys.

#+begin_src sh :tangle ~/.ratpoisonrc
definekey top XF86AudioRaiseVolume exec amixer -q set PCM 5+ unmute; ratpoison -c "echo RaiseVolume +5"
definekey top XF86AudioLowerVolume exec amixer -q set PCM 5- unmute;  ratpoison -c "echo LowerVolume -5"
definekey top XF86AudioMute exec amixer -q set PCM toggle; ratpoison -c "echo [ MUTE ]"
#+end_src

Control EMMS (emacs multimedia system)

#+begin_src sh :tangle ~/.ratpoisonrc
definekey top XF86AudioPlay exec urxvt -e emacsclient -e "(emms-pause)"; ratpoison -c "echo toggle EMMS"
definekey top XF86AudioPrev exec urxvt -e emacsclient -e "(emms-previous)"; ratpoison -c "echo EMMS << Previous song"
definekey top XF86AudioNext exec urxvt -e emacsclient -e "(emms-next)"; ratpoison -c "echo EMMS >> Next song"
#+end_src

** Aliases.

Get the scripts [[https://raw2.github.com/ivoarch/bin/master/mail/gmail.sh][gmail.sh]], [[https://raw2.github.com/ivoarch/bin/master/system/run-skype.sh][run-skype]], [[https://raw2.github.com/ivoarch/bin/master/system/poweroff.sh][poweroff.sh]]

#+begin_src sh :tangle ~/.ratpoisonrc
alias edit exec emacs $HOME/.ratpoisonrc
alias mail exec ~/bin/mail/gmail.sh
alias skype exec ~/bin/system/run-skype.sh
alias enote exec emacsclient -c --eval '(deft)'
alias poweroff exec ~/bin/system/poweroff.sh
#+end_src

** Initial commands.

List of programs that start when ratpoison starts.

#+begin_src sh :tangle ~/.ratpoisonrc
exec urxvt -e screen -RD
exec conkeror
#+end_src
