#+SETUPFILE: ~/.emacs.d/org-templetes/level-0.org
#+TITLE: Мойте Gnu/linux настройки
#+KEYWORDS: linux,setup,emacs,conkeror,ratpoison,minimal software

* Какъв хардуер използвате?
Нетбука който използвам e Acer Aspire One Intel Atom N214, който е със 1.66GHz процесор, 1GB рам памет и поради повреден
хард диск в момента е със външно usb устройство, със капацитет от 16/GB свободно място.

* Какъв софтуер използвате?
Аз съм инсталирал [[https://www.archlinux.org/][archlinux]] (32-бита) на външно usb устройство от 16/GB.

Ползвам минимална, конзолна кoнфигурирана система, което прави моите изисквания за софтуер, изклучително малки.
Единствените приложения от кoито, наистина имaм нужда за да върша работата си, са emacs и conkeror.

** Emacs
Аз прекарвам повечето от времето си в [[https://www.gnu.org/software/emacs/][emacs]], и като всеки новак се старая да права всичко през него. Емакс е моят текстов
редактор, организатор на бележки, калкулатор, четец на пощата ми в Gmail, файлов мениджър и шел. Дори в момента, това го пиша
от емакс :).

** Conkeror
Браузерът е второто най изпoлзвано приложение от мен. Аз съм избрал [[http://conkeror.org/][Conkeror]], високо разтегателен уеб браузер,
използващ емакс клавишни комбинации, написан изцяло в javascript и предназначен за работа предимно с клавиатурата.
Той е единственият браузер който използвам, като изклучим че, когато се нуждая да отворя броузер в терминала, ползвам [[http://w3m.sourceforge.net/][w3m]].

** Ratpoison
Моят мениджър на прозорци е [[http://www.nongnu.org/ratpoison/][ratpoison]]. Той е минималистичен мениджър на прозорци, вдъхновен от [[https://www.gnu.org/software/screen/][Gnu/Screen]] и може да се
контролира 100% чрез клавиатурата, което го прави истински капан за мишки. Без красиви декорации, няма икони, няма тапет
 на десктопа, всеки прозорец се отваря максимално използвайки всеки пиксел от екрана. Той е идеален за моят малък
10 инчов дисплей и е единственият мениджър на прозорци кoйто използвам, като изключим че, когато имам нужда да си поиграя със
летящи прозорци, използвам командата =tmpwm= за да стартира временно [[http://ivoarch.github.io/calavera-wm][calavera-wm]] (друг мениджър на прозорци направен от мен).

** Zsh
Аз използвам [[http://www.zsh.org/][zsh]], като моя интерактивна черупка (шел). Zsh е по добра шел от кoлкото bash, който идва инсталиран в повечето
линукс дистрибуции.

** Git
Аз използвам [[http://git-scm.com/][Git]] от линията на команди (терминал), като source control система. Също така използвам [[http://magit.github.io/][Magit]] който е много
добър емакс интерфейс за git.


-ivo-
