#+TITLE: My ratpoison configuration

** Disable "Welcome" message.

I disabled the default welcome message on start up RP.

#+begin_src sh :tangle ~/.ratpoisonrc
startup_message off
#+end_src

** Unmanaged windows.

Add name to the list of unmanaged windows. Thus, windows of this name will not be managed but allowed to
choose their position themselves.

#+begin_src sh :tangle ~/.ratpoisonrc
unmanage xmessage
unmanage MPlayer
#+end_src

** Appearance.

#+begin_src sh :tangle ~/.ratpoisonrc
set winfmt [%n] %s %t
set winname class
set wingravity c
set maxsizegravity c
#+end_src

*** RP "The best wm for smaller screens!"

I use Ratpoison on tiny 10 inch screen. So I disabled borders/panels etc..

#+begin_src sh :tangle ~/.ratpoisonrc
set padding 0 0 0 0
set barborder 0
set border 0
#+end_src

*** Default font.

I prefer XFT fonts for information stuff.

#+begin_src sh :tangle ~/.ratpoisonrc
set font "DejaVu Sans Mono-10"
#+end_src

** Other commands.

Don't change the cursor into a square when waiting for a key.

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
set waitcursor 0
#+end_src

Bar's timeout in seconds.

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
msgwait 5
#+end_src

** Rudeness.

#+begin_src sh :tangle ~/.ratpoisonrc
# Rudeness is a bitwise or of the following values:
# 1 Transient windows may raise.
# 2 Normal windows may raise.
# 4 New transient windows end up in the foreground.
# 8 New normal windows end up in the foreground.
rudeness 12
#+end_src

** Hooks.

1. Warp the rat to corner of the screen every time you press a top level bound key.
2. Display information about the current window when you switch to a different window.
3. Display information about the current window when you switch to a different frame.

#+begin_src sh :tangle ~/.ratpoisonrc
addhook key banish
addhook switchwin info [%n] %t
addhook switchframe info [%n] %t
#+end_src

** Key bindings.

*** Groups/Windows/Frames

#+begin_src sh :tangle ~/.ratpoisonrc
bind z windows
bind o only
bind u undo
bind d dedicate
bind g groups
#+end_src

*** Using Other Window Managers

#+BEGIN_QUOTE
Use at your own risk ☠!!!
#+END_QUOTE

Temporarily gives control over to [[https://github.com/ivoarch/calavera-wm][Calavera]] window manager and regains control once it has terminated.
I use this when I have to play with floating windows.

#+BEGIN_SRC sh :tangle ~/.ratpoisonrc
bind W tmpwm calavera-wm
#+END_SRC

*** Run-or-raise

Emulate stumpwms run-or-raise with ratpoison.

Get the run-or-raise script form [[https://raw.github.com/ivoarch/bin/master/ratpoison/rp-run-or-raise.sh][here]].

#+begin_src sh :tangle ~/.ratpoisonrc
bind a exec ~/bin/ratpoison/rat_info.sh
bind c exec ~/bin/ratpoison/rp-run-or-raise.sh URxvt 'urxvt'
alias emacs exec ~/bin/ratpoison/rp-run-or-raise.sh Emacs 'emacsclient -ca emacs'
bind e emacs
alias conkeror exec ~/bin/ratpoison/rp-run-or-raise.sh Conkeror 'conkeror'
bind w conkeror
#+end_src

*** Function

Open *man* pages from RP.

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
bind m exec ratpoison -c "exec urxvt -e man $(ratpoison -c "prompt Manpage:")"
#+end_src

Show Dropbox status.

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
bind D exec ratpoison -c "echo `dropbox status`"
#+end_src

Displays the date with a calendar indicating today.

The script comes in the RP contrib dir ([[http://git.savannah.gnu.org/cgit/ratpoison.git/plain/contrib/ratdate.sh][here]]).

#+BEGIN_SRC sh :tangle ~/.ratpoisonrc :padline no
alias time exec /usr/share/ratpoison/ratdate.sh
bind t time
#+END_SRC

Show info script.

Get the ratpoison-info script from [[https://raw2.github.com/ivoarch/bin/master/ratpoison/rat_info.sh][here]].

#+begin_src sh :tangle ~/.ratpoisonrc :padline no
bind I exec ~/bin/ratpoison/rat_info.sh
#+end_src

Toggle =on|off= energy saving.

Get the script from [[https://raw2.github.com/ivoarch/bin/master/system/dpms-toggle.sh][here]].

#+begin_src sh :tangle ~/.ratpoisonrc
alias screensaver exec ~/bin/system/dpms-toggle.sh
bind Pause screensaver
#+end_src

Toggle =on|off= touchpad.

Get the script from [[https://raw2.github.com/ivoarch/bin/master/system/touchpad_toggle][here]].

#+BEGIN_SRC sh :tangle ~/.ratpoisonrc
alias toggletouchpad exec ~/bin/system/touchpad_toggle
bind BackSpace toggletouchpad
#+END_SRC

Take a screenshot.

#+begin_src sh :tangle ~/.ratpoisonrc
alias ratshot exec import -window root png:$HOME/Pictures/Screenshots/ratpoison-$(date +%s)$$.png && ratpoison -c "echo Ratshot saved!"
definekey top Print ratshot
#+end_src

*** Other.

Abort keystrokes.

#+begin_src sh :tangle ~/.ratpoisonrc
definekey root Escape abort
#+end_src

*** Multimedia keys.

Audio/Volume keys.

#+begin_src sh :tangle ~/.ratpoisonrc
definekey top XF86AudioRaiseVolume exec amixer -q set PCM 5+ unmute; ratpoison -c "echo RaiseVolume +5"
definekey top XF86AudioLowerVolume exec amixer -q set PCM 5- unmute;  ratpoison -c "echo LowerVolume -5"
definekey top XF86AudioMute exec amixer -q set PCM toggle; ratpoison -c "echo [ MUTE ]"
#+end_src

Control EMMS (emacs multimedia system)

#+begin_src sh :tangle ~/.ratpoisonrc
definekey top XF86AudioPlay exec urxvt -e emacsclient -e "(emms-pause)"; ratpoison -c "echo toggle EMMS"
definekey top XF86AudioPrev exec urxvt -e emacsclient -e "(emms-previous)"; ratpoison -c "echo EMMS << Previous song"
definekey top XF86AudioNext exec urxvt -e emacsclient -e "(emms-next)"; ratpoison -c "echo EMMS >> Next song"
#+end_src

** Aliases.

1. Edit the ratpoison(rc) config file (requiere emacs).
2. Quickly checks if I have new (g)mail (requiere xmessage).
3. Run skype with GSPCA webcams video support.
4. Create Note (requiere emacs-deft-mode).
5. Start shutdown/reboot menu (requiere xmessage).

Get the scripts (2) [[https://raw2.github.com/ivoarch/bin/master/mail/gmail.sh][gmail.sh]], (3) [[https://raw2.github.com/ivoarch/bin/master/system/run-skype.sh][run-skype]], (5) [[https://raw2.github.com/ivoarch/bin/master/system/poweroff.sh][poweroff.sh]]

#+begin_src sh :tangle ~/.ratpoisonrc
alias edit exec emacs $HOME/.ratpoisonrc
alias mail exec ~/bin/mail/gmail.sh
alias skype exec ~/bin/system/run-skype.sh
alias enote exec emacsclient -c --eval '(deft)'
alias poweroff exec ~/bin/system/poweroff.sh
#+end_src

** Initial commands.

List of programs that start when ratpoison starts.

#+begin_src sh :tangle ~/.ratpoisonrc
exec urxvt -e screen -RD
exec conkeror
#+end_src
